### ISSUE TITLE
How to view the request and response details according to the StatusCodeCoverage.json

### ISSUE THREAD

**Issue by painsAgains** [SeUniVr/RestTestGen#7]
I wanna find the details of requests and responses with status code 500 based on the content of StatusCodeCoverage.json. How do I do this?
Such as I found something in  StatusCodeCoverage.json as following:
`GET /api/v1/configmaps":["500","504","400"]`
I wanna know the content of the request that caused the 500 status code，and its response,.I noticed that there are some json files under th outputpath/Report,but they are too many,and I don't know which one is what I need
![image](https://user-images.githubusercontent.com/49607803/200280245-914f1fd0-02d3-49f8-8537-625cb7e805ba.png)
Hope someone can help me,
Thanks!

**Comment by davidecorradini** [comment]
Hello,
all the HTTP reports are available in the `Report` folder. We are aware this might be confusing and hard to browser, especially when thousands of requests have been sent by RestTestGen. We will work on a better folder arrangement, e.g., by grouping HTTP interactions by status code class. Also, we plan to provide a web interface in the future...
Meanwhile, you could use the `grep` or similar commands to filer out what you need. What I typically do, since I'm working within IntelliJ IDEA, is to right-click on the `Report` folder and select "Find in files...". This action let you perform a text search in all the files in the folder.
Hope this helps!
Best,
Davide

**Comment by painsAgains** [comment]
Thanks! I will try



发自我的iPhone


------------------ Original ------------------
From: Davide Corradini ***@***.***&gt;
Date: Mon,Nov 7,2022 6:07 PM
To: SeUniVr/RestTestGen ***@***.***&gt;
Cc: painsAgains ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [SeUniVr/RestTestGen] How to view the request and responsedetails according to the StatusCodeCoverage.json (Issue #7)





 
Hello,
 all the HTTP reports are available in the Report folder. We are aware this might be confusing and hard to browser, especially when thousands of requests have been sent by RestTestGen. We will work on a better folder arrangement, e.g., by grouping HTTP interactions by status code class. Also, we plan to provide a web interface in the future...
 Meanwhile, you could use the grep or similar commands to filer out what you need. What I typically do, since I'm working within IntelliJ IDEA, is to right-click on the Report folder and select "Find in files...". This action let you perform a text search in all the files in the folder.
 Hope this helps!
 Best,
 Davide
